name: test_install
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  test_install:
    runs-on: ubuntu-latest
    env:
      TERM: "linux"
    strategy:
      fail-fast: false
      matrix:
        commands:
          # Enter toasttool starting from the main menu with \n as the delimiter. 
          - "17\n0\n1\n\n99\n99\n99"  # Install, run, update, update system,      press ENTER to continue, back to main menu, quit
          - "17\n0\n2\n\n99\n99\n99"  # Install, run, update, update toasttool, press ENTER to continue, back to main menu, quit
          - "17\n1\n1\n"  # Install, run, uninstall, press ENTER to continue
          - "99"  # Install, run, quit
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: 'pip'
      - run: pip install --upgrade pip
      - run: pwd && ls -hal
      - run: sudo ./install.sh 1
      - run: pwd && ls -hal
      # Typing "1" will allow us to manually enter the filepath to toasttool.
      # Provide the filepath ${HOME}/work/toasttool/toasttool
      # Type the matrix.commands.
      - run: echo -e "1\n${HOME}/work/toasttool/toasttool\n${{ matrix.commands }}\n" | toasttool
      - run: pwd && ls -hal

